#ifndef LARGE_DBC_CONTRACT_H
#define LARGE_DBC_CONTRACT_H

#include <stdint.h>

/*
 * Large DBC P0 contract only.  Binary files are serialized field by field;
 * these constants must not be used to read or write packed C structs.
 */

#define LARGE_DBC_CONTRACT_VERSION 1u

#define LARGE_DBC_SOURCE_MAX_BYTES 262144u
#define LARGE_DBC_CATALOG_MAX_MESSAGES 2048u
#define LARGE_DBC_CATALOG_MAX_SIGNALS 2048u
#define LARGE_DBC_ACTIVE_MAX_MESSAGES 64u
#define LARGE_DBC_ACTIVE_MAX_SIGNALS 128u
#define LARGE_DBC_SELECTION_BITMAP_BYTES (LARGE_DBC_CATALOG_MAX_SIGNALS / 8u)

#define LARGE_DBC_MESSAGE_NAME_MAX_BYTES 31u
#define LARGE_DBC_SIGNAL_NAME_MAX_BYTES 31u
#define LARGE_DBC_KEY_MAX_BYTES 63u
#define LARGE_DBC_UNIT_MAX_BYTES 31u
#define LARGE_DBC_QUERY_MAX_BYTES 63u
#define LARGE_DBC_PARSER_LINE_BYTES 512u

#define LARGE_DBC_API_PAGE_ITEMS 8u
#define LARGE_DBC_HTTP_JSON_BODY_BYTES 3072u
#define LARGE_DBC_HTTP_JSON_PAYLOAD_MAX_BYTES 3071u
#define LARGE_DBC_HTTP_RESPONSE_SEGMENT_BYTES 512u
#define LARGE_DBC_HTTP_REALTIME_ITEM_WORST_BYTES 263u
#define LARGE_DBC_HTTP_ENVELOPE_WORST_BYTES 512u
#define LARGE_DBC_SIGNAL_STALE_AFTER_MS 3000u
#define LARGE_DBC_SELECTION_UPDATE_MAX_ORDINALS 32u
#define LARGE_DBC_SELECTION_REQUEST_BODY_BYTES 512u
#define LARGE_DBC_UPLOAD_CHUNK_BYTES 512u
#define LARGE_DBC_UPLOAD_IDLE_TIMEOUT_MS 5000u
#define LARGE_DBC_UPLOAD_TOTAL_TIMEOUT_MS 120000u

#define LARGE_DBC_LOG_SAMPLE_PERIOD_MIN_MS 100u
#define LARGE_DBC_LOG_SAMPLE_PERIOD_MAX_MS 10000u
#define LARGE_DBC_MAX_LOG_ROWS_PER_SECOND 20u

/* Final firmware must retain this flash reserve after text + data. */
#define LARGE_DBC_FLASH_TOTAL_BYTES 131072u
#define LARGE_DBC_FLASH_RESERVE_BYTES 4096u
#define LARGE_DBC_FLASH_MAX_USED_BYTES \
  (LARGE_DBC_FLASH_TOTAL_BYTES - LARGE_DBC_FLASH_RESERVE_BYTES)

/* Persistent runtime slots, value slots, and all new static scratch combined. */
#define LARGE_DBC_STATIC_RAM_BUDGET_BYTES 65536u
#define LARGE_DBC_NEW_TASK_COUNT 0u
#define LARGE_DBC_FREERTOS_HEAP_INCREMENT_BUDGET_BYTES 0u
#define LARGE_DBC_FREERTOS_MIN_EVER_FREE_HEAP_BYTES 4096u
#define LARGE_DBC_TASK_MIN_STACK_MARGIN_BYTES 256u
#define LARGE_DBC_MAX_AUTOMATIC_OBJECT_BYTES 512u

/*
 * The current branch is authorized only for isolated laboratory acceptance.
 * This is not a credential scheme.  A production build must disable mutation
 * until the separate production write-authorization contract is implemented.
 */
#define LARGE_DBC_WRITE_AUTH_POLICY_LAB_ISOLATED_LAN 1u
#define LARGE_DBC_WRITE_AUTH_POLICY \
  LARGE_DBC_WRITE_AUTH_POLICY_LAB_ISOLATED_LAN

/* All multibyte fields use fixed little-endian encoding. */
#define LARGE_DBC_BYTE_ORDER_LITTLE_ENDIAN 1u

/* IEEE CRC-32, reflected polynomial 0x04C11DB7. */
#define LARGE_DBC_CRC32_REFLECTED_POLYNOMIAL UINT32_C(0xEDB88320)
#define LARGE_DBC_CRC32_INITIAL_VALUE UINT32_C(0xFFFFFFFF)
#define LARGE_DBC_CRC32_FINAL_XOR UINT32_C(0xFFFFFFFF)

/* Binary magic values as decoded from little-endian byte order. */
#define LARGE_DBC_MANIFEST_MAGIC UINT32_C(0x4D434244) /* DBCM */
#define LARGE_DBC_INDEX_MAGIC UINT32_C(0x49434244) /* DBCI */
#define LARGE_DBC_SELECTION_MAGIC UINT32_C(0x53434244) /* DBCS */

enum LargeDbcManifestObjectKind {
  LARGE_DBC_MANIFEST_OBJECT_CANDIDATE = 1u,
  LARGE_DBC_MANIFEST_OBJECT_ACTIVE = 2u
};

enum LargeDbcFrameRequirement {
  LARGE_DBC_FRAME_CLASSIC_OR_FD = 0u,
  LARGE_DBC_FRAME_FD_REQUIRED = 1u
};

enum LargeDbcSignalFlags {
  LARGE_DBC_SIGNAL_FLAG_IDE = 1u << 0,
  LARGE_DBC_SIGNAL_FLAG_FD_REQUIRED = 1u << 1,
  LARGE_DBC_SIGNAL_FLAG_MOTOROLA = 1u << 2,
  LARGE_DBC_SIGNAL_FLAG_SIGNED = 1u << 3
};

/* 64-byte manifest. CRC covers bytes [0, 60). */
#define LARGE_DBC_MANIFEST_SIZE 64u
#define LARGE_DBC_MANIFEST_MAGIC_OFFSET 0u
#define LARGE_DBC_MANIFEST_VERSION_OFFSET 4u
#define LARGE_DBC_MANIFEST_HEADER_SIZE_OFFSET 6u
#define LARGE_DBC_MANIFEST_OBJECT_KIND_OFFSET 8u
#define LARGE_DBC_MANIFEST_FLAGS_OFFSET 9u
#define LARGE_DBC_MANIFEST_GENERATION_OFFSET 12u
#define LARGE_DBC_MANIFEST_SOURCE_SIZE_OFFSET 20u
#define LARGE_DBC_MANIFEST_SOURCE_CRC32_OFFSET 24u
#define LARGE_DBC_MANIFEST_INDEX_SIZE_OFFSET 28u
#define LARGE_DBC_MANIFEST_INDEX_CRC32_OFFSET 32u
#define LARGE_DBC_MANIFEST_SELECTION_SIZE_OFFSET 36u
#define LARGE_DBC_MANIFEST_SELECTION_CRC32_OFFSET 40u
#define LARGE_DBC_MANIFEST_SELECTED_COUNT_OFFSET 44u
#define LARGE_DBC_MANIFEST_SELECTED_MESSAGE_COUNT_OFFSET 46u
#define LARGE_DBC_MANIFEST_CATALOG_MESSAGE_COUNT_OFFSET 48u
#define LARGE_DBC_MANIFEST_CATALOG_SIGNAL_COUNT_OFFSET 50u
#define LARGE_DBC_MANIFEST_CRC32_OFFSET 60u
#define LARGE_DBC_MANIFEST_CRC32_COVERED_BYTES 60u

/* 80-byte index header. Header CRC covers bytes [0, 76). */
#define LARGE_DBC_INDEX_HEADER_SIZE 80u
#define LARGE_DBC_INDEX_MAGIC_OFFSET 0u
#define LARGE_DBC_INDEX_VERSION_OFFSET 4u
#define LARGE_DBC_INDEX_HEADER_SIZE_OFFSET 6u
#define LARGE_DBC_INDEX_MESSAGE_RECORD_SIZE_OFFSET 8u
#define LARGE_DBC_INDEX_SIGNAL_RECORD_SIZE_OFFSET 10u
#define LARGE_DBC_INDEX_FLAGS_OFFSET 12u
#define LARGE_DBC_INDEX_SOURCE_SIZE_OFFSET 16u
#define LARGE_DBC_INDEX_SOURCE_CRC32_OFFSET 20u
#define LARGE_DBC_INDEX_MESSAGE_COUNT_OFFSET 24u
#define LARGE_DBC_INDEX_SIGNAL_COUNT_OFFSET 28u
#define LARGE_DBC_INDEX_MESSAGE_RECORDS_OFFSET_OFFSET 32u
#define LARGE_DBC_INDEX_MESSAGE_RECORDS_SIZE_OFFSET 36u
#define LARGE_DBC_INDEX_MESSAGE_RECORDS_CRC32_OFFSET 40u
#define LARGE_DBC_INDEX_SIGNAL_RECORDS_OFFSET_OFFSET 44u
#define LARGE_DBC_INDEX_SIGNAL_RECORDS_SIZE_OFFSET 48u
#define LARGE_DBC_INDEX_SIGNAL_RECORDS_CRC32_OFFSET 52u
#define LARGE_DBC_INDEX_TOTAL_SIZE_OFFSET 56u
#define LARGE_DBC_INDEX_HEADER_CRC32_OFFSET 76u
#define LARGE_DBC_INDEX_HEADER_CRC32_COVERED_BYTES 76u

/* 16-byte message record. */
#define LARGE_DBC_INDEX_MESSAGE_RECORD_SIZE 16u
#define LARGE_DBC_MESSAGE_RECORD_NORMALIZED_ID_OFFSET 0u
#define LARGE_DBC_MESSAGE_RECORD_SOURCE_LINE_OFFSET 4u
#define LARGE_DBC_MESSAGE_RECORD_FIRST_SIGNAL_OFFSET 8u
#define LARGE_DBC_MESSAGE_RECORD_SIGNAL_COUNT_OFFSET 10u
#define LARGE_DBC_MESSAGE_RECORD_FLAGS_OFFSET 12u
#define LARGE_DBC_MESSAGE_RECORD_DECLARED_LENGTH_OFFSET 13u

/* 160-byte signal record. Key/unit arrays are NUL-padded. */
#define LARGE_DBC_INDEX_SIGNAL_RECORD_SIZE 160u
#define LARGE_DBC_SIGNAL_RECORD_ORDINAL_OFFSET 0u
#define LARGE_DBC_SIGNAL_RECORD_MESSAGE_ORDINAL_OFFSET 2u
#define LARGE_DBC_SIGNAL_RECORD_NORMALIZED_ID_OFFSET 4u
#define LARGE_DBC_SIGNAL_RECORD_FLAGS_OFFSET 8u
#define LARGE_DBC_SIGNAL_RECORD_START_BIT_OFFSET 10u
#define LARGE_DBC_SIGNAL_RECORD_BIT_LENGTH_OFFSET 12u
#define LARGE_DBC_SIGNAL_RECORD_DECLARED_LENGTH_OFFSET 13u
#define LARGE_DBC_SIGNAL_RECORD_KEY_LENGTH_OFFSET 14u
#define LARGE_DBC_SIGNAL_RECORD_UNIT_LENGTH_OFFSET 15u
#define LARGE_DBC_SIGNAL_RECORD_FACTOR_OFFSET 16u
#define LARGE_DBC_SIGNAL_RECORD_VALUE_OFFSET_OFFSET 24u
#define LARGE_DBC_SIGNAL_RECORD_MINIMUM_OFFSET 32u
#define LARGE_DBC_SIGNAL_RECORD_MAXIMUM_OFFSET 40u
#define LARGE_DBC_SIGNAL_RECORD_DEFINITION_HASH_OFFSET 48u
#define LARGE_DBC_SIGNAL_RECORD_SOURCE_LINE_OFFSET 56u
#define LARGE_DBC_SIGNAL_RECORD_SOURCE_OFFSET_OFFSET 60u
#define LARGE_DBC_SIGNAL_RECORD_KEY_OFFSET 64u
#define LARGE_DBC_SIGNAL_RECORD_KEY_BYTES 64u
#define LARGE_DBC_SIGNAL_RECORD_UNIT_OFFSET 128u
#define LARGE_DBC_SIGNAL_RECORD_UNIT_BYTES 32u

/* 64-byte selection header followed by the fixed 2048-bit bitmap. */
#define LARGE_DBC_SELECTION_HEADER_SIZE 64u
#define LARGE_DBC_SELECTION_TOTAL_SIZE \
  (LARGE_DBC_SELECTION_HEADER_SIZE + LARGE_DBC_SELECTION_BITMAP_BYTES)
#define LARGE_DBC_SELECTION_MAGIC_OFFSET 0u
#define LARGE_DBC_SELECTION_VERSION_OFFSET 4u
#define LARGE_DBC_SELECTION_HEADER_SIZE_OFFSET 6u
#define LARGE_DBC_SELECTION_TOTAL_SIZE_OFFSET 8u
#define LARGE_DBC_SELECTION_BITMAP_SIZE_OFFSET 12u
#define LARGE_DBC_SELECTION_CANDIDATE_GENERATION_OFFSET 16u
#define LARGE_DBC_SELECTION_SOURCE_SIZE_OFFSET 24u
#define LARGE_DBC_SELECTION_SOURCE_CRC32_OFFSET 28u
#define LARGE_DBC_SELECTION_CATALOG_SIGNAL_COUNT_OFFSET 32u
#define LARGE_DBC_SELECTION_SELECTED_COUNT_OFFSET 34u
#define LARGE_DBC_SELECTION_BITMAP_CRC32_OFFSET 36u
#define LARGE_DBC_SELECTION_GENERATION_OFFSET 40u
#define LARGE_DBC_SELECTION_HEADER_CRC32_OFFSET 60u
#define LARGE_DBC_SELECTION_HEADER_CRC32_COVERED_BYTES 60u

/* Candidate token is 16 hex generation + '-' + 8 hex size + '-' + 8 hex CRC. */
#define LARGE_DBC_CANDIDATE_TOKEN_CHARS 34u
#define LARGE_DBC_CANDIDATE_TOKEN_BUFFER_BYTES 35u

/*
 * definition_hash is FNV-1a-64 over the exact 42-byte version-1 stream:
 * version:u8, normalized_id:u32le, flags:u8, declared_length:u8,
 * start_bit:u16le, bit_length:u8, then factor/offset/min/max as four
 * canonical IEEE-754 binary64 little-endian values. NaN/Inf are rejected and
 * negative zero is serialized as positive zero. The hash is compatibility
 * evidence, not an authentication primitive.
 */
#define LARGE_DBC_DEFINITION_FORMAT_VERSION 1u
#define LARGE_DBC_DEFINITION_SERIALIZED_BYTES 42u
#define LARGE_DBC_FNV1A64_OFFSET_BASIS UINT64_C(14695981039346656037)
#define LARGE_DBC_FNV1A64_PRIME UINT64_C(1099511628211)
#define LARGE_DBC_DEFINITION_HASH_GOLDEN_V1 UINT64_C(0x9C93DAD64DB4DC23)

#endif
